version: "3.3"
services:
  app:
    image: "regisclient:prd"
    ports:
      - "5000:5000"
  regis:
    image: "registration:prd"
    ports:
      - "5000:5000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=passwordrm
      - DB_DATABASE=ocm_db
      - DB_HOST=db
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ${PWD}:/app
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - ocm_regisdb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_ROOT_PASSWORD=passwordrm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwordrm
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
      - POSTGRES_DB=ocm_db
      - POSTGRES_PORT=5432
volumes:
  ocm_regisdb_data:
